import type { GameId } from "@/lib/arcade/engine";

export type Cabinet = { id: GameId; number: string; title: string; subtitle: string; genre: string; description: string; objective: string; controls: string; action: string; multiplayer: boolean; };
export const cabinets: readonly Cabinet[] = [
  { id: "bounce", number: "01", title: "BREAKPOINT", subtitle: "Everything has a breaking point.", genre: "MAGNETIC BRICK BREAKER", description: "An electron loose inside the machine. Tear through layers of memory, bend the rebound, catch it in your magnetic field. Then let it rip.", objective: "Clear the memory banks. Chain hits for a ×5 multiplier. Each cleared sector earns an extra ball.", controls: "Move: A / D, arrows or drag. Space launches. Hold Space as the ball returns to catch it. Catch costs 25 charge.", action: "LAUNCH / MAGNET", multiplayer: false },
  { id: "pong", number: "02", title: "PHOSPHOR PONG", subtitle: "The shortest path is never straight.", genre: "GRAVITY-WELL DUEL", description: "A moving singularity bends every rally. Read the curve, hold your nerve, then overcharge the return. One tube. Two ends. No excuses.", objective: "First to seven. Time an overcharge just before impact for a faster return. Play the machine or a friend.", controls: "Solo: W / S or arrows; Space overcharges. Two players: W / S + Space for green; ↑ / ↓ + Enter for amber. Drag a paddle on touch.", action: "OVERCHARGE", multiplayer: true },
  { id: "snake", number: "03", title: "OUROBOROS", subtitle: "Your past is trying to kill you.", genre: "PHASE-SHIFT SNAKE", description: "Eat the signal. Become the maze. For 1.8 seconds, phase through your own history and slip across the edges of the screen. Spend that escape wisely.", objective: "Collect amber signals. Phase costs 65 charge; food restores it. Two-player mode ends when a snake crashes.", controls: "Move: WASD, arrows or the direction pad. Space phases. Two players: WASD + Space for green; arrows + Enter for amber.", action: "PHASE SHIFT", multiplayer: true },
  { id: "under", number: "04", title: "UNDER THE TERMINAL", subtitle: "Something is still running down there.", genre: "DAILY DESCENT", description: "Below the command line, the abandoned processes are awake. Find a key, reach the lift and descend. A different dungeon every UTC day. The same one for everyone.", objective: "Find the amber key, then the lift. Walk into a bug to attack. A pulse clears nearby bugs. Enemies move only when you do.", controls: "Move / attack: WASD, arrows or the direction pad. Space sends a test pulse (45 charge). Moving restores charge. Green crosses repair two health.", action: "TEST PULSE", multiplayer: false },
  { id: "signal", number: "05", title: "DEAD SIGNAL", subtitle: "You are the last live pixel.", genre: "VECTOR SURVIVAL", description: "The noise is closing in. Your beam hunts automatically; you concentrate on surviving. Thread the swarm, build a kill chain, discharge the whole screen around you.", objective: "Survive escalating waves. Your beam aims at the nearest threat. Kills build a score multiplier and recharge your pulse.", controls: "Move: WASD, arrows, drag or the direction pad. Space discharges a pulse around you (65 charge). You have three hull points.", action: "DISCHARGE", multiplayer: false },
  { id: "poker", number: "06", title: "CIRCUIT POKER", subtitle: "Play the hand. Break the circuit.", genre: "DRAW-POKER PUZZLE", description: "Five cards. Two redraws. Three hands to meet a rising target. Hold the pieces of a perfect circuit, or bank what you have before the machine asks too much.", objective: "Beat each circuit's target in three hands. Each hand allows two redraws. Bank your hand to score it and deal the next.", controls: "Tap cards or press 1–5 to hold them. Space redraws the unheld cards. Enter banks your hand. No money, betting or accounts.", action: "REDRAW", multiplayer: false },
];
export const collectionCopy = {
  title: "THE ARCADE", label: "FergusOS arcade", subtitle: "You found the other side of the glass.",
  intro: "Six experiments in phosphor. Zero coins required.",
  transfer: "TRANSFERRING CONTROL", arrival: "ENTERING THE ARCADE", skip: "Skip sequence", exit: "Back to terminal",
  insert: "SELECT A CABINET", free: "FREE PLAY", soundOn: "Sound on", soundOff: "Sound off", play: "Start solo run", local: "Two players · one screen", online: "Connect a friend", back: "All cabinets",
  pause: "Pause", resume: "Resume", restart: "Play again", paused: "SYSTEM PAUSED", over: "SIGNAL LOST", won: "CIRCUIT COMPLETE", score: "FINAL SCORE", board: "HIGH SCORES", loading: "Reading the board…", empty: "The board is empty. Set the first score.", unavailable: "The board is offline. Your game still works.",
  submit: "Post score", submitting: "Posting…", saved: "Your score is on the board.", initials: "Your three initials", boardNote: "Casual, client-reported scores. No accounts. Solo runs only.",
  privacy: "Games run in your browser. Posting shares only your three initials and score. Initials are saved on this device only when you post. The forget command clears them.",
  netPrivacy: "A direct connection shares your IP address with your opponent. Cloudflare STUN helps the browsers connect. There is no relay for game traffic; some networks cannot connect.",
  netTitle: "LINK THE CABINETS", netIntro: "Open this game on both devices. The host sends an invite; the other player returns an answer. Then the host connects.",
  create: "Create invite", join: "Answer invite", connect: "Connect cabinets", copy: "Copy", copied: "Copied", invite: "Invite / answer code", netWait: "Waiting for your friend…", netConnecting: "Connecting the cabinets…", netReady: "Cabinets linked. The host starts the match.", netFailure: "The cabinets could not connect. Try again or play on one screen.", disconnected: "Your opponent disconnected. Return to the cabinets to reconnect.", networkUnsupported: "This browser does not support direct multiplayer. Two players can still share this screen.",
  match: "Start linked match", pendingRun: "Preparing score entry…", notRanked: "Two-player matches are for bragging rights. The boards rank solo runs.",
} as const;
