export const meetingCopy = {
  contact: "Contact",
  getInTouch: "Get in touch",
  coffee: "Grab a coffee?",
  call: "Jump on a call?",
  coffeeDetail: "Somewhere in Dublin. 30 minutes.",
  callDetail: "From wherever you are. 30 minutes.",
  intro: "Pick a time. I'll confirm by email.",
  timezone: "Irish time · Europe/Dublin",
  duration: "30 minutes",
  day: "Choose a day",
  time: "Choose a time",
  previous: "Previous month",
  next: "Next month",
  weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
  available: "Available",
  unavailable: "Unavailable",
  selected: "Your request",
  selectTime: "Select a time to continue",
  name: "Your name",
  email: "Your email",
  note: "Anything I should know?",
  optional: "Optional",
  submit: "Request this time",
  sending: "Sending request…",
  sent: "Request sent.",
  sentBody: "I'll confirm the time and details by email.",
  failed: "That didn't send. Your details are still here. Try again or email me directly.",
  fallback: "Send by email",
  message: "Prefer to write?",
  back: "Back to contact",
  another: "Choose another time",
  noScript: "Choose a date and time (Irish time)",
  errors: {
    kind: "Choose coffee or a call.",
    slot: "Choose an available time at least a day from now.",
    note: "Keep the note under 2,000 characters.",
    plainText: "Use plain text for the note.",
  },
} as const;
