/** Product copy shared by the five work surfaces, separate from the tool registry. */
export const workbenchCopy = {
  title: "Small tools. Useful results.",
  description: "Find the words that sound unlike you. Turn a year into a landscape. See who comes back. Five free tools, ready to try.",
  back: "All tools",
  open: "Open tool",
  limits: "How to read the result",
  details: "Method and limitations",
  privacyDetails: "Connection details",
  noAccount: "No account. No installation.",
  example: "Start with an example or bring your own data.",
  tools: {
    "headline-check": { purpose: "Make your headline readable", input: "A URL or a little HTML", output: "Compare the visible words with extracted text", category: "Web", preview: "HTML → readable words" },
    drift: { purpose: "Keep your writing sounding like you", input: "Your writing + a draft", output: "Find changed habits and sentences to revisit", category: "Writing", preview: "Your voice / this draft" },
    relief: { purpose: "Turn your year into a landscape", input: "Dated CSV or GitHub commits", output: "Explore your terrain. Export PNG, SVG or STL", category: "Making", preview: "52 weeks × 24 hours" },
    overlap: { purpose: "Find the people you both know", input: "Two LinkedIn connection exports", output: "A searchable list of shared connections", category: "Connections", preview: "Two lists. Common ground." },
    "second-visit": { purpose: "Find out who comes back", input: "A bookings or orders CSV", output: "Retention curves and useful follow-up lists", category: "Business", preview: "First visit → next visit" },
  } as Record<string, { purpose: string; input: string; output: string; category: string; preview: string }>,
};

export const localOverlapCopy = {
  local: "Compare two files",
  peer: "Connect with someone",
  intro: "Have both exports? Compare them here in seconds. Both files stay in this tab. Only use files you have permission to read.",
  first: "First connection list",
  second: "Second connection list",
  choose: "Choose a LinkedIn CSV",
  demo: "Try example lists",
  clear: "Clear both files",
  example: "Example lists. These people are invented.",
  shared: "In both lists",
  onlyA: "Only in the first",
  onlyB: "Only in the second",
  search: "Find a connection",
  searchPlaceholder: "Search names or profile links",
  download: "Download this list",
  empty: "No connections match this view.",
  waiting: "Choose both files to reveal your overlap.",
  reading: "Reading your file…",
  failed: "That file has no usable LinkedIn profiles. Choose a Connections.csv export with a URL column.",
  tooLarge: "Choose a CSV smaller than 5 MB.",
  readFailed: "This browser could not read the file. Please choose it again.",
  exportFailed: "The download could not be created. Your lists are still here; try again.",
  exact: "Exact profile matches. Names come from the first list for shared connections.",
  count: (used: number, skipped: number) => `${used.toLocaleString("en-IE")} profiles${skipped ? ` · ${skipped} rows skipped or repeated` : ""}`,
  showing: (visible: number, total: number) => `Showing ${visible} of ${total.toLocaleString("en-IE")} matches. Search to narrow the list; the download includes all matches in this view.`,
  peerIntro: "Keep one file on each person's computer. The browsers exchange salted profile hashes, not names. The other person learns your list size and IP address and can test guesses against the hashes. Direct connections can fail on restrictive networks.",
  peerDetails: "What the other person and the connection service can see",
};

export const headlineLabCopy = {
  heading: "Try it on your HTML",
  intro: "Paste a heading or a page's source. Nothing is uploaded and pasted code is never executed.",
  label: "HTML to inspect",
  broken: "Split-letter example",
  clean: "Readable example",
  sample: "Build something worth reading",
  limit: "Up to 100,000 characters. This checks source HTML, not a rendered page.",
  waiting: "Paste HTML to see both readings.",
  browser: "Visible text model",
  crawler: "Extracted text model",
  tooLarge: "That source is too large. Paste just the heading and its surrounding HTML (under 100,000 characters).",
};

export const driftWorkbenchCopy = {
  samples: (pieces: number, words: number) => `${pieces} pieces · ${words.toLocaleString("en-IE")} words`,
  draft: (words: number) => `${words.toLocaleString("en-IE")} words · 150 needed for a distance`,
  addPiece: "Add another piece",
  storage: "Saving and deleting your profile",
  method: "Reference and measurement details",
  stale: "Your text has changed. Rebuild the profile or measure the draft to update this report.",
  oversized: "That is too much text for this browser workbench. Use up to 50 sample pieces, under 100,000 characters in total, and a draft under 30,000 characters.",
  demo: "Example report",
  yours: "Your writing report",
  within: "Within your observed range",
  above: "Further from your profile than your sample pieces",
  below: "Closer to your profile than your sample pieces",
  rangeNote: "This compares with the variation in your own samples. It is a guide to review, not a quality score or an AI verdict.",
  download: "Download report",
  downloadFailed: "The report download failed. Your text is still here; try again.",
};

export const reliefWorkbenchCopy = {
  explore: "Explore the landscape",
  week: "Week",
  hour: "Hour of the day",
  cell: (week: number, hour: number, count: number) => `Week ${week}, ${String(hour).padStart(2, "0")}:00 · ${count} events`,
  guide: "Peaks are busy hours. Valleys are quiet ones. Move the controls to read the original count behind any part of the terrain.",
  details: "How the terrain and exports are made",
  stale: "No new landscape is ready. The previous view is shown for reference; exports are paused until a file is accepted or you return to the demo.",
  newDemo: "Try another landscape",
  source: "Landscape on display",
};

export const secondVisitWorkbenchCopy = {
  optional: "More columns: spend, products and contact details",
  settings: "Adjust the model assumptions",
  setup: "Review the file and column mapping",
  results: "Your retention report",
  example: "Example report from invented customers",
  horizon: "Return within",
  days: "days",
  chooseColumn: "Choose a column",
  actions: "Choose your next action",
  period: "Customers and observation window",
  failed: "The analysis stopped. Please reload this page and choose your file again. Nothing was uploaded.",
  downloadFailed: "The download could not be created. Your report is still here; try again.",
  customers: "Customers",
  visits: "Attended visits",
  returned: "Came back",
  groups: "Where your customers stand",
  groupNote: "These groups describe the booking patterns in your file. They are model estimates, not predictions checked against future visits.",
  emptyGroup: "No customers in this group",
  chartDays: "Days after the first visit",
  mappings: { customer: "Customer identifier", date: "Visit or order date", amount: "Amount spent", slotStart: "Session start", capacity: "Session capacity", status: "Booking status", town: "Customer town", country: "Country", product: "Product", party: "Group size", credits: "Remaining credits", consent: "Marketing permission", email: "Email address", phone: "Phone number" } as Record<string, string>,
};
