/**
 * Builds lib/tools/second-visit/towns.generated.ts from GeoNames.
 *
 * Run rarely, by hand, on a machine with a network. The generated file is
 * committed, so a fresh clone never needs this and CI never runs it.
 *
 *   node scripts/second-visit/build-towns.mjs
 *   node scripts/second-visit/build-towns.mjs --min-population 1000
 *
 * Source: https://download.geonames.org/export/dump/, licensed CC BY 4.0. The
 * attribution that licence requires is printed on the tool's page and is in
 * `content/tools/second-visit.ts`, not only in this comment.
 *
 * Two countries. IE is the whole of it; GB is filtered to admin1 `NIR`, because
 * a sauna in Donegal has customers from Derry and without them every one of
 * those rows falls to `unknown` instead of `visitor`.
 *
 * The zip is unpacked with `tar -xf`, which is bsdtar on Windows 10 and later
 * and GNU tar with libarchive elsewhere, and handles a zip in both. That is
 * deliberately not a dependency: this script runs about once a year.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const BASE = "https://download.geonames.org/export/dump";
const args = process.argv.slice(2);
const minPopulation = Number(args[args.indexOf("--min-population") + 1]) || 500;
/** Capitals and administrative seats come in whatever their population says. */
const ALWAYS = new Set(["PPLC", "PPLA", "PPLA2"]);

const work = mkdtempSync(join(tmpdir(), "sv-towns-"));

async function download(name) {
  const url = `${BASE}/${name}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} came back ${response.status}`);
  const path = join(work, name);
  writeFileSync(path, Buffer.from(await response.arrayBuffer()));
  console.log(`downloaded ${name}, ${(await (await fetch(url)).arrayBuffer()).byteLength} bytes`);
  return path;
}

function unzip(zipPath, member) {
  execFileSync("tar", ["-xf", zipPath, "-C", work, member], { stdio: "inherit" });
  return join(work, member);
}

const adminPath = await download("admin1CodesASCII.txt");
const admin = new Map();
for (const line of readFileSync(adminPath, "utf8").split("\n")) {
  const [code, name] = line.split("\t");
  if (code && name) admin.set(code, name);
}

const rows = [];
for (const [country, file, filter] of [
  ["IE", "IE.zip", () => true],
  ["GB", "GB.zip", (cols) => cols[10] === "NIR"],
]) {
  const zip = await download(file);
  const txt = unzip(zip, file.replace(".zip", ".txt"));
  let kept = 0;
  for (const line of readFileSync(txt, "utf8").split("\n")) {
    const cols = line.split("\t");
    if (cols.length < 15) continue;
    if (cols[6] !== "P") continue;
    if (!filter(cols)) continue;
    const population = Number(cols[14]) || 0;
    if (population < minPopulation && !ALWAYS.has(cols[7])) continue;
    const county = country === "GB" ? "Northern Ireland" : (admin.get(`IE.${cols[10]}`) ?? "");
    rows.push([cols[1], county, country, Number(cols[4]), Number(cols[5]), population]);
    kept++;
  }
  console.log(`${file}: kept ${kept}`);
}

// One row per name, the largest settlement winning, so "Newport" is the one
// most people mean and the other is unreachable rather than randomly chosen.
const byName = new Map();
for (const row of rows) {
  const key = row[0].toLowerCase();
  const existing = byName.get(key);
  if (!existing || row[5] > existing[5]) byName.set(key, row);
}
const final = [...byName.values()].sort((a, b) => b[5] - a[5] || a[0].localeCompare(b[0]));

const body = final
  .map(([n, c, cc, lat, lng, pop]) =>
    `  [${JSON.stringify(n)},${JSON.stringify(c)},"${cc}",${lat},${lng},${pop}],`,
  )
  .join("\n");

writeFileSync(
  "lib/tools/second-visit/towns.generated.ts",
  `// GENERATED by scripts/second-visit/build-towns.mjs. Do not edit by hand.
//
// Source: GeoNames (https://www.geonames.org/), IE.zip and the Northern Ireland
// rows of GB.zip, licensed CC BY 4.0. The attribution that licence requires is
// printed on /tools/second-visit and lives in content/tools/second-visit.ts.
//
// Populated places only (feature class P) with a population of at least
// ${minPopulation}, plus every capital and administrative seat whatever its
// population. One row per name, the largest settlement winning.
//
// Built ${new Date().toISOString().slice(0, 10)}. ${final.length} places.

/** name, county, country, latitude, longitude, population */
export type TownRow = readonly [string, string, string, number, number, number];

export const TOWN_ROWS: readonly TownRow[] = [
${body}
];
`,
  "utf8",
);

rmSync(work, { recursive: true, force: true });
console.log(`wrote ${final.length} places`);

