export const studioCopy = {
  local: "FergusOS · local studios",
  files: "Choose files",
  folder: "Choose a folder",
  example: "Explore an example",
  reset: "Reset",
  search: "Search",
  cancel: "Cancel",
  save: "Save",
  back: "Back",
  clear: "Clear",
  loading: "Reading your files…",
  empty: "Nothing matches these filters.",
  atlas: {
    eyebrow: "ATLAS / CONNECTED KNOWLEDGE",
    title: "Find the thread.",
    intro:
      "A living map of your files. Pull a node, follow a connection, discover what belongs together.",
    drop: "Drop files, a folder or a ZIP here",
    limits:
      "Up to 1,000 files / 80 MB. Text, code, PDF and office documents are readable; other files still appear with metadata. Archives are expanded once. Scanned PDFs need OCR elsewhere.",
    github: "Public GitHub repository",
    githubNote:
      "Fetch sends requests to GitHub. Public repositories only, up to 1,000 tree entries; reads up to 100 text files (8 MB total). Upload a ZIP for fuller coverage.",
    fetch: "Fetch repository",
    fit: "Fit map",
    pause: "Pause physics",
    reduced: "Reduced motion · static layout",
    exportError: "The browser could not export the map image.",
    resume: "Resume physics",
    focus: "Focus neighbours",
    all: "Whole map",
    pin: "Pin node",
    unpin: "Release node",
    inspect: "File inspector",
    connections: "Why these are connected",
    noSelection:
      "Select any point to inspect the file and its connections. Drag points to reshape the map; drag empty space to pan. Scroll or pinch to zoom.",
    export: "Save map + extracted text",
    image: "Save map image",
    reference: "References",
    terms: "Shared words",
    containment: "Folders",
    query: "Search files and contents",
    list: "Accessible file list",
    noLinks: "No connections found in the supplied files.",
    read: "Extracted text",
    metadata: "Metadata only",
    status: "Import coverage",
    spread: "Spacing",
    load: "Open a saved map",
    source:
      "Source files stay in this tab. A saved map includes extracted text, so review it before sharing.",
  },
  lore: {
    eyebrow: "GROUP LORE / THE ARCHIVE",
    title: "Every group has a rhythm.",
    intro:
      "Find the late nights, the running jokes and the conversations you forgot you had.",
    upload: "Import chat (.txt, .json, .zip)",
    dateOrder: "WhatsApp date order",
    paste: "Paste an export",
    analyse: "Read this chat",
    rhythm: "The weekly rhythm",
    rhythmNote:
      "Tap a square to read that hour’s messages. Times use this browser’s timezone; WhatsApp dates have no timezone information.",
    people: "The voices",
    phrases: "Things you keep saying",
    archive: "Message explorer",
    portrait: "Make a portrait",
    summary: "Download anonymous summary",
    pseudo: "Use pseudonyms",
    start: "From date",
    end: "To date",
    search: "Search message text",
    person: "Participant",
    all: "All voices",
    more: "Show 50 more",
    clear: "Clear filters",
    heatClear: "Clear hour filter",
    session:
      "A conversation starts after a gap of more than 30 minutes. Counts describe this export, not relationships.",
    privacy:
      "Pseudonyms change speaker labels only. The explorer still contains the original message text. Portraits and anonymous summaries contain counts, with no quotations or names.",
    portraitTitle: "The shape of us",
    portraitDownload: "Download portrait SVG",
    importNote:
      "WhatsApp text; Telegram or DiscordChatExporter JSON; ZIP containing one chat export. 10 MB of chat text, up to 30 MB ZIP. Media is not analysed.",
  },
  music: {
    eyebrow: "RESONANCE / PLAY THE MACHINE",
    title: "Make something you didn’t plan.",
    intro: "Four voices. Sixteen steps. An instrument to get lost in.",
    play: "Play sequence",
    stop: "Stop sound",
    preset: "Sound worlds",
    bpm: "Tempo",
    scale: "Scale",
    root: "Key",
    volume: "Output",
    swing: "Swing",
    cutoff: "Brightness",
    delay: "Echo",
    pad: "Performance pad",
    padHelp:
      "Drag to shape brightness (left to right) and echo (bottom to top). Changes happen while you play.",
    stageHelp:
      "Tap a pendulum to pluck it. Drag up or down to change its note. Keyboard A S D F plays the four voices while this instrument is focused.",
    save: "Save patch",
    load: "Open patch",
    render: "Render 8 bars to WAV",
    rendering: "Rendering your audio…",
    random: "New pattern",
    clear: "Clear steps",
    mute: "Mute",
    solo: "Solo",
    decay: "Decay",
    pan: "Pan",
    wave: "Tone",
    note: "Note",
    ready: "Ready to play",
    playing: "Sequence running",
    keys: ["A", "S", "D", "F"],
    presets: ["After hours", "Glasshouse", "Slow tide", "Subterranean"],
    hint: "Sound starts with a deliberate press. Leaving this tab stops it. WAV rendering includes eight bars plus the release tail.",
  },
};
