// Supporting interface labels for the five local studios.
export const studioLabels = {
  Atlas: {
    githubComOwnerRepository: "github.com/owner/repository",
    fileType: "File type",
    allTypes: "All types",
    bytes: " bytes",
    links: " links",
    show60MoreFiles: "Show 60 more files",
  },
  GraphCanvas: {
    interactiveFileGraphUseTheFileList:
      "Interactive file graph. Use the file list to select nodes. Arrow keys pan; plus and minus zoom; zero fits the map.",
    nodes: " nodes · ",
    visibleConnections: " visible connections",
  },
  GroupLore: {
    dayMonthYear: "Day / month / year",
    monthDayYear: "Month / day / year",
    readingMessages: "Reading messages…",
    text01WhenYouShowUp: "01 / WHEN YOU SHOW UP",
    messagesInTheCompleteExportDarkerQuieter:
      " messages in the complete export · darker = quieter",
    text02WhoSHere: "02 / WHO’S HERE",
    text03TheRunningThreads: "03 / THE RUNNING THREADS",
    noRepeatedTwoWordPhrasesInThis:
      "No repeated two-word phrases in this export.",
    matches: " matches",
    anonymousActivityPortraitPreview: "Anonymous activity portrait preview",
  },
  PocketRedact: {
    cancel: "Cancel",
    documentPages: "Document pages",
    masks: " masks",
    redactionEditor: "Redaction editor",
    drawOrMoveRedactionMasks: "Draw or move redaction masks",
    exactText: "Exact text",
    emailLikeText: "Email-like text",
    phoneLongNumbers: "Phone / long numbers",
    masksAcross: " masks across ",
    pages: " pages",
    page: "Page ",
  },
  ProveIt: {
    chooseCase: "Choose case",
    case: "CASE ",
    caseFile: "CASE FILE ",
    of: "of ",
    creditsLeft: " credits left",
    selectYourWorkingExplanation: "Select your working explanation",
    investigateObserve: "INVESTIGATE / OBSERVE",
    observations: "OBSERVATIONS / ",
    evidence: "EVIDENCE ",
    credits: " CREDITS",
    yourPrediction: "Your prediction: ",
    beforeThisTestExplanation: "Before this test: explanation ",
    confidence: "% confidence",
    youCanCommitAtAnyTimeA:
      "You can commit at any time. A correct guess earns less than a conclusion supported by evidence.",
    whatEachExplanationPredicted: "What each explanation predicted",
    investigation: "Investigation",
    explanation: "Explanation ",
    beforeTest: "Before test ",
    at: " at ",
    final: "Final: ",
    at2: " at ",
    scoring35ForTheConclusion40For:
      "Scoring: 35 for the conclusion, 40 for evidence that separates the explanations, up to 15 for budget efficiency, and up to 10 for confidence accuracy (one minus squared error). This is a game score.",
  },
  Resonance: {
    voice: "Voice ",
    minor: "Minor",
    major: "Major",
    pentatonic: "Pentatonic",
    sequencer: "SEQUENCER",
    shapeVoice: "Shape voice ",
    glass: "Glass",
    warm: "Warm",
    reed: "Reed",
    brightnessEcho: "BRIGHTNESS → / ECHO ↑",
  },
} as const;
