/** Resonance's words. Read through `studioCopy.music` and `studioLabels.Resonance`. */
export const musicCopy = {
  play: "Play sequence",
  stop: "Stop sound",
  preset: "Sound worlds",
  bpm: "Tempo",
  scale: "Scale",
  root: "Key",
  volume: "Output",
  swing: "Swing",
  cutoff: "Brightness",
  delay: "Echo",
  pad: "Performance pad",
  padHelp:
    "Drag to shape brightness (left to right) and echo (bottom to top). Changes happen while you play.",
  stageHelp:
    "Tap a pendulum to pluck it. Drag up or down to change its note. Keyboard A S D F plays the four voices while this instrument is focused.",
  save: "Save patch",
  load: "Open patch",
  exports: "Keep this patch",
  render: "Render 8 bars to WAV",
  rendering: "Rendering your audio…",
  random: "New pattern",
  clear: "Clear steps",
  mute: "Mute",
  solo: "Solo",
  decay: "Decay",
  pan: "Pan",
  wave: "Tone",
  note: "Note",
  ready: "Ready to play",
  playing: "Sequence running",
  keys: ["A", "S", "D", "F"],
  presets: ["After hours", "Glasshouse", "Slow tide", "Subterranean"],
  hint: "Sound starts with a deliberate press. Leaving this tab stops it. WAV rendering includes eight bars plus the release tail.",
};

export const musicLabels = {
  voice: "Voice ",
  minor: "Minor",
  major: "Major",
  pentatonic: "Pentatonic",
  sequencer: "Steps",
  shapeVoice: "Shape voice ",
  glass: "Glass",
  warm: "Warm",
  reed: "Reed",
  brightnessEcho: "Brightness → · Echo ↑",
} as const;
