export const common = {
  example: "Load example",
  download: "Download",
  reset: "Reset",
  import: "Import file",
  results: "Results",
  run: "Run",
  empty: "No results for these inputs.",
  minutes: "min",
  hours: "hours",
  sample: "EXAMPLE DATA",
  live: "LIVE FORECAST",
  source: "Source",
  remove: "Remove",
  name: "Name",
  export: "Export JSON",
  input: "Input",
  before: "Before",
  after: "After",
  count: "Count",
  print: "Print",
  close: "Close",
  choose: "Choose a file",
  working: "Working…",
};
export const copy = {
  bottleneck: {
    mode: "Service model",
    modes: ["Continuous queue", "Scheduled sessions"],
    fields: [
      "Arrivals / hour",
      "Open for (minutes)",
      "Service stations",
      "Service / session (minutes)",
      "Turnover (minutes)",
      "People / session / station",
      "Random seed",
    ],
    run: "Simulate",
    pin: "Pin as baseline",
    csv: "Download people CSV",
    metrics: [
      "Average wait (started)",
      "Completed before closing",
      "Unserved at closing",
      "90th percentile wait",
    ],
    chart: "People waiting through the day",
    axis: "Minutes after opening",
    people: "First 80 arrivals",
    columns: ["Person", "Arrives", "Starts", "Finishes"],
    notServed: "Not started",
    baseline: "Pinned baseline",
    baselineNote:
      "The amber line is your baseline. Keep the seed and demand unchanged to compare capacity against identical arrivals.",
  },
  weather: {
    place: "Location",
    places: ["Dublin", "Bray", "Galway", "Cork"],
    fetch: "Fetch live forecast",
    duration: "Window length (hours)",
    rain: "Maximum rain / hour (mm)",
    wind: "Maximum wind (km/h)",
    temperature: "Minimum temperature (°C)",
    daylight: "Daylight only",
    calendar: "Save window to calendar",
    title: "Suitable windows",
    none: "No complete window matches. Relax a condition or try a shorter duration.",
    sampleNote:
      "Synthetic weather for exploring the controls. It is not a forecast.",
    liveNote: "Fetched from Open-Meteo. Times are displayed in Europe/Dublin.",
    fetching: "Fetching forecast…",
    timeline: "Hourly conditions",
    wet: "rain",
    source: "Weather data: Open-Meteo (CC BY 4.0)",
    terms: "API terms",
    event: "Outdoor time · Good Window",
  },
  trace: {
    label: "JSON array or one JSON object per line",
    analyse: "Inspect trace",
    filter: "Show events",
    filters: ["All", "Errors", "Claims", "Repeated tools"],
    metrics: ["Tool calls", "Failures", "Repeated calls", "Claims"],
    timeline: "Run timeline",
    link: "Supporting event",
    unlinked: "No evidence linked",
    export: "Download annotated review",
    note: "Review note",
    noteHint: "What did you verify, and what remains unproven?",
    schema: "Import format",
    schemaText:
      "Each record needs at (ISO time) and type (tool, claim or note). Tool records need name, input and status (ok or error); durationMs is optional. Claims and notes need text. Download the example to adapt it.",
    download: "Download example JSONL",
    example: [
      {
        at: "2026-09-06T09:00:00Z",
        type: "note",
        text: "Task: fix a contact form that loses fast submissions.",
      },
      {
        at: "2026-09-06T09:01:00Z",
        type: "tool",
        name: "shell",
        input: "npm test",
        status: "ok",
        durationMs: 3800,
      },
      {
        at: "2026-09-06T09:02:00Z",
        type: "tool",
        name: "browser",
        input: "submit form with autofill",
        status: "error",
        durationMs: 2200,
      },
      {
        at: "2026-09-06T09:03:00Z",
        type: "tool",
        name: "shell",
        input: "npm test",
        status: "ok",
        durationMs: 3600,
      },
      {
        at: "2026-09-06T09:04:00Z",
        type: "claim",
        text: "The contact form is fixed and all tests pass.",
      },
      {
        at: "2026-09-06T09:05:00Z",
        type: "tool",
        name: "http",
        input: "compare fast and slow POST against provider log",
        status: "ok",
        durationMs: 1600,
      },
      {
        at: "2026-09-06T09:06:00Z",
        type: "claim",
        text: "Both submissions now reached the mail provider.",
      },
    ],
  },
  alignment: {
    steps: ["Your answers", "Compare files"],
    intro:
      "Answer before opening your partner’s file. Download your answers and ask them to do the same.",
    person: "Your name / alias",
    export: "Download my answers",
    partner: "Partner’s answer file",
    compare: "Reveal differences",
    agenda: "Conversation agenda",
    same: "These answers match. Explore the reasoning behind them anyway.",
    question: "Question",
    you: "You",
    them: "Partner",
    note: "Decision / next experiment",
    save: "Download discussion record",
    questions: [
      {
        key: "priority",
        label: "Next 90 days: learn quickly (1) or earn revenue (5)?",
        numeric: true,
      },
      {
        key: "pace",
        label: "Weekly pace: sustainable (1) or an intense sprint (5)?",
        numeric: true,
      },
      {
        key: "risk",
        label: "Spending: protect runway (1) or invest ahead (5)?",
        numeric: true,
      },
      {
        key: "scope",
        label: "Product: narrow and excellent (1) or broad platform (5)?",
        numeric: true,
      },
      { key: "customer", label: "Who is the first customer?", numeric: false },
      {
        key: "stop",
        label: "What evidence would make you stop?",
        numeric: false,
      },
    ],
    sampleA: {
      priority: 2,
      pace: 3,
      risk: 2,
      scope: 1,
      customer: "Independent sauna operators",
      stop: "Ten interviews without a repeated painful problem",
    },
    sampleB: {
      priority: 5,
      pace: 4,
      risk: 4,
      scope: 4,
      customer: "Wellness chains",
      stop: "Six months without revenue",
    },
  },
  estimate: {
    model: "Model",
    models: ["Event surplus (€)", "Project cost (€)", "Cash runway (months)"],
    columns: ["Assumption", "Low", "Likely", "High"],
    run: "Run 2,000 scenarios",
    seed: "Random seed",
    metrics: ["10th percentile", "Median", "90th percentile"],
    histogram: "Distribution of simulated outcomes",
    sensitivity: "Which assumption moves the result?",
    note: "Sensitivity varies one input from low to high while holding the others at likely. The 10th–90th band contains 80% of these simulated outcomes, given your assumptions.",
    formula: {
      event: "guests × (ticket − variable cost) − fixed cost",
      project: "days × day rate + extra costs",
      runway: "cash ÷ (monthly costs − monthly income)",
    },
    labels: {
      guests: "Guests",
      ticket: "Ticket price (€)",
      variable: "Cost per guest (€)",
      fixed: "Fixed cost (€)",
      days: "Days",
      rate: "Day rate (€)",
      extra: "Extra costs (€)",
      cash: "Cash (€)",
      costs: "Monthly costs (€)",
      income: "Monthly income (€)",
    },
    defaults: {
      event: {
        guests: { min: 30, likely: 60, max: 100 },
        ticket: { min: 20, likely: 25, max: 30 },
        variable: { min: 5, likely: 8, max: 12 },
        fixed: { min: 600, likely: 850, max: 1200 },
      },
      project: {
        days: { min: 5, likely: 12, max: 25 },
        rate: { min: 400, likely: 500, max: 650 },
        extra: { min: 0, likely: 500, max: 1800 },
      },
      runway: {
        cash: { min: 25000, likely: 30000, max: 35000 },
        costs: { min: 4500, likely: 5500, max: 7000 },
        income: { min: 500, likely: 1500, max: 3000 },
      },
    },
  },
  fair: {
    roster: "Players, one per line. Optional skill 1–5 after a comma.",
    courts: "Courts",
    rounds: "Total rounds",
    played: "Completed rounds to preserve",
    seed: "Draw seed",
    generate: "Create / replan draw",
    round: "Round",
    court: "Court",
    rest: "Resting",
    balance: "Games per player",
    note: "To handle someone leaving, keep completed rounds, remove their name above and replan. Names must be unique.",
    csv: "Download draw CSV",
    sample:
      "Fergus,3\nAoife,4\nAlex,2\nNiamh,3\nSam,4\nBea,2\nCian,3\nOrla,4\nConor,2\nRory,3\nMaeve,4\nBen,2\nErin,3",
  },
  prove: {
    case: "Case",
    budget: "Budget remaining",
    hypothesis: "Your current hypothesis",
    confidence: "Confidence (%)",
    investigate: "Choose an investigation",
    evidence: "Evidence collected",
    commit: "Commit to conclusion",
    correct: "Correct conclusion",
    incorrect: "That conclusion does not fit the case",
    score: "Investigation score",
    answer: "Explanation",
    again: "Replay this case",
    empty: "No evidence collected yet.",
    cost: "cost",
  },
  chat: {
    label: "WhatsApp text export (day/month/year)",
    analyse: "Discover the lore",
    metrics: ["Messages", "Participants", "Most active hour"],
    people: "Who kept it going?",
    hours: "When the group comes alive",
    phrases: "Recurring phrases",
    months: "Activity over time",
    pseudo: "Use pseudonyms",
    portrait: "Download activity portrait (SVG)",
    summary: "Download aggregate JSON",
    empty: "No repeated two-word phrases found.",
    sample: Array.from(
      { length: 84 },
      (_, i) =>
        `${String((i % 27) + 1).padStart(2, "0")}/0${7 + Math.floor(i / 42)}/2026, ${String([8, 12, 18, 21, 22][i % 5]).padStart(2, "0")}:${String(i % 60).padStart(2, "0")} - ${["Fergus", "Aoife", "Sam", "Niamh"][i % 4]}: ${["quick pint after work?", "who is bringing the snacks", "quick pint sounds good", "the usual spot then", "running five minutes late", "who is bringing the speaker", "see you at the usual spot"][i % 7]}`,
    ).join("\n"),
  },
  redact: {
    upload: "Open PDF, PNG or JPEG",
    instruction:
      "Drag across an area to cover it. Or enter a rectangle in page pixels below. Every page is exported as a fresh image inside a new PDF.",
    page: "Page",
    rect: "Add a rectangle by coordinates",
    fields: ["Left (px)", "Top (px)", "Width (px)", "Height (px)"],
    add: "Cover this rectangle",
    undo: "Undo last cover",
    clear: "Clear this page",
    pdf: "Export flattened PDF",
    png: "Export this page as PNG",
    review: "Reopened export preview",
    reviewNote:
      "This preview is rendered from the PDF bytes you downloaded. Check every page. The output contains raster images, so text cannot be selected or recovered from a hidden text layer.",
    open: "Open exported PDF in a new tab",
    busy: "Rendering document…",
    sampleTitle: "SAMPLE INVOICE",
    sampleBody: [
      "Invoice: INV-2026-0042",
      "Customer: Alex Example",
      "Email: alex@example.test",
      "Address: 42 Example Road, Dublin",
      "Service: Workshop session",
      "Amount due: €240.00",
      "Bank reference: DEMO-1234-5678",
      "Prepared for a redaction demonstration.",
    ],
    bounds: "Rectangle coordinates must fit within this page.",
    marks: "Covered areas",
  },
  calendar: {
    noInput:
      "No calendar loaded yet. Open the example or import a calendar to start.",
    sample: "EXAMPLE WEEK · These meetings are fictional.",
    week: "Week beginning",
    upload: "Import .ics calendar",
    example: "Load example week",
    buffer: "Buffer around meetings (minutes)",
    block: "Minimum focus block (minutes)",
    metrics: ["Meeting hours", "Focus hours", "Focus blocks"],
    calendar: "Week planner",
    free: "Focus",
    busy: "Busy",
    move: "Try moving a meeting",
    event: "Meeting",
    shift: "Shift (minutes)",
    apply: "Apply hypothetical move",
    export: "Download proposed week .ics",
    focusExport: "Download focus blocks .ics",
    original: "Restore imported week",
    none: "No focus blocks meet these conditions.",
    note: "Working hours: Monday–Friday, 09:00–17:00 in this browser’s timezone. The proposed export is a copy; it does not update your calendar.",
    titles: [
      "Team check-in",
      "Customer interview",
      "Design review",
      "Supplier call",
      "Planning",
      "Weekly wrap-up",
    ],
  },
  atlas: {
    upload: "Open source ZIP or snapshot JSON",
    compare: "Compare another snapshot / ZIP",
    export: "Download metrics snapshot",
    metrics: ["Source files", "Lines", "Bytes"],
    city: "Code city",
    help: "Each building is a file: height follows line count, width follows byte size. Select a building to inspect it. Generated and vendor files are excluded.",
    filter: "Filter path",
    details: "Selected file",
    delta: "Changes against baseline",
    baseline: "Set current as baseline",
    columns: ["Path", "Before", "After", "Change"],
    empty: "No matching source files.",
    sample: [
      { path: "app/page.tsx", lines: 120 },
      { path: "app/tools/page.tsx", lines: 210 },
      { path: "app/api/contact/route.ts", lines: 180 },
      { path: "components/Terminal.tsx", lines: 340 },
      { path: "components/PhosphorScreen.tsx", lines: 620 },
      { path: "components/Navigation.tsx", lines: 95 },
      { path: "lib/physics.ts", lines: 780 },
      { path: "lib/audio.ts", lines: 510 },
      { path: "lib/contact.ts", lines: 260 },
      { path: "lib/seo.ts", lines: 380 },
      { path: "content/profile.ts", lines: 90 },
      { path: "content/tools.ts", lines: 150 },
      { path: "tests/contact.test.ts", lines: 410 },
      { path: "tests/physics.test.ts", lines: 310 },
    ],
    sampleNote:
      "Synthetic source files inspired by a portfolio’s shape; these are not measurements of the live repository.",
  },
  resonance: {
    play: "Play instrument",
    stop: "Stop",
    preset: "Patch",
    presets: ["Slow orbit", "Three against four", "Rain on glass"],
    note: "MIDI note",
    period: "Period (seconds)",
    voice: "Voice",
    volume: "Volume",
    save: "Download patch",
    load: "Import patch JSON",
    muted: "Stopped. Press Play to enable sound.",
    playing: "Playing. Crossing the centre plucks a note.",
    help: "Each pendulum crosses the centre twice per period. Change the ratios to hear the pattern evolve. Tab away to stop the instrument.",
    patches: [
      [
        { note: 60, period: 4 },
        { note: 64, period: 5 },
        { note: 67, period: 6 },
        { note: 72, period: 8 },
      ],
      [
        { note: 57, period: 3 },
        { note: 64, period: 4 },
        { note: 69, period: 6 },
        { note: 76, period: 8 },
      ],
      [
        { note: 72, period: 1.7 },
        { note: 76, period: 2.3 },
        { note: 79, period: 3.1 },
        { note: 84, period: 4.7 },
      ],
    ],
  },
};
